"""A management option that names a drug nothing has heard of must not read as checked.

``screen_text`` resolves the drugs a model-written management option names and evaluates each
against the chart. That is the whole of Critical Safety Rule #3 for generated output, and it has
one blind spot, which is what happens when the resolution finds nothing:

    named = await self.resolver.rows_named_in(text)
    if not named:
        return []

An empty list. The same empty list "Advise rest and oral fluids" produces, and the same empty
list a correctly-screened option with no conflicts produces. Synthesis reads it as unconflicted,
leaves the option at the case autonomy tier, titles it "Guideline-supported management option"
and hangs a citation off it. The clinician is looking at a recommendation for a drug that does
not exist, presented exactly like one that was checked against their patient's allergies.

This is the third time this system has had to make the distinction between "found nothing" and
"could not look" — ``check_unevaluated_medications`` and ``check_unevaluated_allergies`` are the
first two — and the first time the unreadable text was written by us. The option text is
generated by whichever provider is configured, in this deployment often a small free model, and
a plausible drug name is exactly the kind of thing such a model invents fluently.

The companion failure is the dose: levothyroxine is dispensed and dosed in micrograms, so
"Levothyroxine 50 mg" is a fluent sentence, a plausible number, and 500 times the largest
strength the product is made in.

Both checks are offline, deterministic and deliberately under-reporting; ``test_dose_text`` pins
the parser's judgement, and this file pins what the vocabulary and the pipeline do with it.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import select

from app.agents.state import CaseState, GuidelineChunkRef, ManagementOption
from app.agents.synthesis import build_suggestions
from app.models.patient import Patient
from app.models.user import Account
from app.services.safety_service import SafetyService

# No module-level asyncio mark: ``asyncio_mode = "auto"`` already runs the async tests here, and
# the synthesis tests at the bottom are deliberately synchronous — ``build_suggestions`` is a
# pure function of the case state, which is what makes the tier and the title testable without
# a database.

# A drug that does not exist, written the way a model writes one: a plausible stem, a plausible
# dose, a plausible schedule.
HALLUCINATED = (
    "Guidelines support considering Cardizemol 40 mg twice daily for rate control, with review "
    "after one week."
)
# The same sentence about a drug that does exist and is in the seeded vocabulary.
REAL = (
    "Guidelines support considering Metformin 500 mg twice daily alongside lifestyle modification."
)


async def _patient(db) -> Patient:
    account_id = (await db.execute(select(Account.id))).scalars().first()
    if account_id is None:
        account = Account(email=f"dose-{uuid.uuid4().hex}@example.com", password_hash="x")
        db.add(account)
        await db.flush()
        account_id = account.id
    patient = Patient(
        account_id=account_id,
        full_name="Dose Integrity",
        consent_given=True,
        consent_given_at=datetime.now(UTC),
    )
    db.add(patient)
    await db.flush()
    return patient


def _types(flags) -> list[str]:
    return [f.check_type for f in flags]


# --------------------------------------------------------------------------- the drug name


async def test_an_option_naming_a_drug_the_vocabulary_does_not_know_says_so(db):
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(patient.id, HALLUCINATED)

    assert "unverified_drug_name" in _types(flags), (
        f"a prescription for a drug that does not exist screened clean; flags were {_types(flags)}"
    )
    flag = next(f for f in flags if f.check_type == "unverified_drug_name")
    assert "Cardizemol" in flag.summary
    assert flag.details["unverified_names"] == ["Cardizemol"]
    assert flag.details["doses"] == ["40 mg"]


async def test_the_unverified_flag_is_a_warning_and_never_a_hard_block(db):
    """A hard block is Rule #3's instrument for a documented conflict, and it demands a
    documented override. Spending it on our own text's defects is how a hard block stops meaning
    what it means — the escalation to flag-for-review is what carries this finding."""
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(patient.id, HALLUCINATED)

    flag = next(f for f in flags if f.check_type == "unverified_drug_name")
    assert flag.severity == "warning"
    assert flag.is_hard_block is False
    assert flag.details["evaluated"] is False


async def test_an_option_naming_a_real_drug_raises_no_integrity_flag(db):
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(patient.id, REAL)

    assert "unverified_drug_name" not in _types(flags)
    assert "implausible_dose" not in _types(flags)


async def test_a_real_drug_does_not_vouch_for_an_invented_one_beside_it(db):
    """The failure the clause window exists for.

    A model that names a genuine drug and then an invented one in the same sentence must not
    have the first launder the second. Anchoring is asked of the dose's own clause, not of the
    text.
    """
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(
        patient.id, "Guidelines support considering Metformin 500 mg and Zaltrexil 20 mg daily."
    )

    flag = next(f for f in flags if f.check_type == "unverified_drug_name")
    assert flag.details["unverified_names"] == ["Zaltrexil"]


async def test_prose_that_prescribes_nothing_still_screens_clean(db):
    """The pre-existing contract. Most management options name no drug at all — supportive care,
    safety-netting, review — and none of them may acquire a flag from this."""
    patient = await _patient(db)
    service = SafetyService(db)

    assert await service.screen_text(patient.id, "Advise rest and oral fluids.") == []
    assert await service.screen_text(patient.id, "") == []
    assert (
        await service.screen_text(
            patient.id,
            "Guidelines support considering supportive management with careful isotonic fluid "
            "therapy titrated to the plasma-leak phase.",
        )
        == []
    )


async def test_a_dose_with_no_name_in_front_of_it_raises_nothing(db):
    """Under-reporting on purpose: only the canonical prescription shape is judged."""
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(
        patient.id, "Titrate the dose to 500 mg as tolerated."
    )

    assert flags == []


async def test_a_laboratory_value_in_the_option_text_is_not_a_prescription(db):
    """Guideline prose reports a creatinine in mg/dL in the same paragraph it recommends a drug
    in mg. Reading the first as a dose would flag the analyte's name as an invented drug."""
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(
        patient.id,
        "Guidelines support considering review when serum creatinine exceeds 1.5 mg/dL.",
    )

    assert flags == []


# --------------------------------------------------------------------------- the dose


async def test_a_dose_a_thousand_times_the_products_strength_is_reported(db):
    """Levothyroxine is seeded at 50 mcg and 100 mcg; the sentence says 50 mg."""
    patient = await _patient(db)

    flags = await SafetyService(db).screen_text(
        patient.id, "Guidelines support considering Levothyroxine 50 mg once daily."
    )

    flag = next(f for f in flags if f.check_type == "implausible_dose")
    assert flag.severity == "critical"
    assert flag.is_hard_block is False
    assert flag.details["drug"] == "Levothyroxine"
    assert flag.details["dose_text"] == "50 mg"
    # Measured against the largest strength the molecule is listed in, not the first row found.
    assert flag.details["largest_listed_strength"] == "100mcg"


async def test_an_ordinary_therapeutic_dose_is_not_reported(db):
    """Paracetamol is seeded at 500 mg and 650 mg; a 1 g dose and a 4 g day are both ordinary."""
    patient = await _patient(db)
    service = SafetyService(db)

    for text in (
        "Guidelines support considering Paracetamol 1 g every six hours.",
        "Guidelines support considering Paracetamol 4 g/day as the maximum.",
        "Guidelines support considering Ceftriaxone 2 g IV once daily.",
        "Guidelines support considering Salbutamol 200 mcg inhaled as required.",
    ):
        flags = await service.screen_text(patient.id, text)
        assert "implausible_dose" not in _types(flags), f"{text!r} produced {_types(flags)}"


async def test_a_drug_with_no_mass_strength_falls_back_to_the_absolute_ceiling(db):
    """Insulin is listed as 100U/mL — no mass to compare against, so only the absolute ceiling
    applies, and it is set above every dose in use rather than guessed at."""
    patient = await _patient(db)
    service = SafetyService(db)

    ordinary = await service.screen_text(
        patient.id, "Guidelines support considering Insulin degludec 20 units at night."
    )
    assert "implausible_dose" not in _types(ordinary)


# ------------------------------------------------------------------- what the clinician sees


def _option(text: str, flags: list[dict]) -> CaseState:
    state = CaseState(patient_id=str(uuid.uuid4()), presenting_complaint="chest pain")
    state.autonomy_tier = "suggestive"
    state.management_options.append(
        ManagementOption(
            text=text,
            citations=[
                GuidelineChunkRef(
                    section_id="STW-1",
                    source="icmr",
                    document_title="Standard Treatment Workflow",
                    heading="Management",
                    snippet="…",
                    score=0.9,
                    corpus_version="1",
                    page_range=None,
                )
            ],
            sufficient_support=True,
            safety_flags=flags,
        )
    )
    return state


def test_an_unverified_option_is_escalated_and_titled_for_what_is_wrong_with_it():
    """Not "conflicts with this patient's record" — there is nothing in the chart to look for.

    The escalation is the same; the sentence is different, because sending a clinician to hunt
    for a conflict that does not exist wastes the engagement the tier is asking for.
    """
    state = _option(
        "Guidelines support considering Cardizemol 40 mg twice daily.",
        [
            {
                "check_type": "unverified_drug_name",
                "severity": "warning",
                "is_hard_block": False,
                "summary": "…",
            }
        ],
    )

    card = next(s for s in build_suggestions(state) if s["output_type"] == "management")

    assert card["autonomy_tier"] == "flag_for_review"
    assert card["title"] == "Management option — the drug or dose it names could not be verified"
    assert card["evidence"]["drug_verified"] is False
    assert card["is_hard_block"] is False


def test_a_patient_conflict_still_outranks_an_integrity_problem_in_the_title():
    """Both present: the conflict with the patient's own record is the more dangerous finding
    and keeps the headline, with the integrity flag carried underneath it."""
    state = _option(
        "Guidelines support considering Paracetamol 500 mg and Cardizemol 40 mg.",
        [
            {
                "check_type": "allergy_conflict",
                "severity": "hard_block",
                "is_hard_block": True,
                "summary": "…",
            },
            {
                "check_type": "unverified_drug_name",
                "severity": "warning",
                "is_hard_block": False,
                "summary": "…",
            },
        ],
    )

    card = next(s for s in build_suggestions(state) if s["output_type"] == "management")

    assert card["title"].endswith("conflicts with this patient's record")
    assert card["is_hard_block"] is True
    assert card["evidence"]["drug_verified"] is False


def test_a_clean_option_keeps_the_case_tier_and_the_plain_title():
    state = _option("Guidelines support considering Metformin 500 mg twice daily.", [])

    card = next(s for s in build_suggestions(state) if s["output_type"] == "management")

    assert card["autonomy_tier"] == "suggestive"
    assert card["title"] == "Guideline-supported management option"
    assert card["evidence"]["drug_verified"] is True
