"""Intake question/answer models — the Triage agent's adaptive clarifying interview (P2-02)."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.types import GUID
from app.models.base import Base, CreatedAtMixin, UUIDPrimaryKeyMixin

_QUESTION_TYPES = ("red_flag", "relevant_negative", "clarifying", "history", "exam")


class IntakeQuestion(UUIDPrimaryKeyMixin, CreatedAtMixin, Base):
    """A single highest-information-gain clarifying question generated by the Triage agent."""

    __tablename__ = "intake_questions"
    __table_args__ = (
        CheckConstraint(
            f"question_type IN ({', '.join(repr(t) for t in _QUESTION_TYPES)})",
            name="ck_intake_questions_type",
        ),
    )

    session_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("reasoning_sessions.id"), nullable=False, index=True
    )
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    question_type: Mapped[str] = mapped_column(String(30), nullable=False, default="clarifying")
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    sequence_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    info_gain_score: Mapped[float | None] = mapped_column(nullable=True)
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class IntakeAnswer(UUIDPrimaryKeyMixin, CreatedAtMixin, Base):
    """Clinician's response to an IntakeQuestion. **One per question, enforced here.**

    ``ReasoningService.submit_answers`` already treats a second answer to a question as a
    correction that rewrites the first, and says why at length: ``_rebuild_intake_state``
    collapses answers with ``answers_by_q[a.question_id] = a.answer_text`` over an *unordered*
    query, so with two rows for one question the one that reaches the engine is whatever order
    the database returned. That is clinical input — ``agents.util.text_blob`` feeds affirmative
    answers to the can't-miss sentinel and drops the keywords of anything answered "no" — so on a
    ``red_flag`` question it decides whether a time-critical diagnosis is screened in or out, and
    the two rows cannot be told apart afterwards: rows written in one transaction share a
    ``created_at`` and the primary key is a random UUID rather than a sequence.

    That rule was enforced only in Python, by reading the existing answers and updating the row
    it found. Read-then-insert, so two submissions that overlap in the window both read no
    existing answer and both insert — and the ordinary ways to produce a second submission are a
    double-clicked Submit, a retried request, and the same case open in two rooms. A "yes" and a
    "no" to one red-flag question then sat in the table together with nothing to choose between
    them.

    So the invariant is the database's. The loser of the race is refused rather than written, and
    ``submit_answers`` re-reads and applies its answer as the correction it was.
    """

    __tablename__ = "intake_answers"
    __table_args__ = (
        # A unique *index* rather than a UniqueConstraint so the schema the ORM builds and the
        # one migration 0024 builds are the same object under the same name — the same reason
        # ``uq_lab_results_observation`` is declared this way.
        Index("uq_intake_answers_question", "question_id", unique=True),
    )

    # No ``index=True``: the unique index above answers everything a plain one on the same
    # column would, and the second index only costs a write on every answer recorded.
    question_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("intake_questions.id"), nullable=False
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("reasoning_sessions.id"), nullable=False, index=True
    )
    answer_text: Mapped[str] = mapped_column(Text, nullable=False)
