/**
 * The frontend renders text it did not write, and it must keep escaping all of it.
 *
 * Almost everything this UI displays is attacker-influenceable in the ordinary sense: a drug
 * name read off a scan by OCR, a clinical note typed by whoever had the chart open, an agent's
 * rationale generated by an LLM from that same material. React escapes interpolated text by
 * default, which is why none of that is a problem today — and why the one API that opts out of
 * it is the thing worth guarding.
 *
 * `dangerouslySetInnerHTML` is the whole surface. There is no sanitiser in this app's
 * dependency tree (no DOMPurify, no markdown renderer), so a single use of it would be raw
 * injection of clinical text into the DOM, with nothing in front. The name is a good warning
 * and a bad control: it reads as scary in review and as ordinary in a diff.
 *
 * These are source-level assertions rather than rendering tests on purpose. A rendering test
 * proves one component escapes its input; this proves no component *can* fail to, which is
 * the property that actually holds the line as screens are added.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOTS = [
  resolve(__dirname, '..'), // apps/web/src
  resolve(__dirname, '../../../../packages/ui/src'),
];

const SOURCE_EXTENSIONS = ['.ts', '.tsx'];

function sourceFiles(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === '.next') continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      found.push(...sourceFiles(path));
    } else if (SOURCE_EXTENSIONS.some((ext) => entry.endsWith(ext))) {
      found.push(path);
    }
  }
  return found;
}

/** Every .ts/.tsx under the web app and the shared component library, excluding this file. */
function allSources(): { path: string; text: string }[] {
  return ROOTS.flatMap((root) =>
    sourceFiles(root)
      .filter((path) => path !== __filename)
      .map((path) => ({ path: relative(resolve(__dirname, '../../../..'), path), text: readFileSync(path, 'utf8') })),
  );
}

describe('the escaping React gives us by default is not opted out of anywhere', () => {
  it('has no dangerouslySetInnerHTML', () => {
    const offenders = allSources()
      .filter(({ text }) => text.includes('dangerouslySetInnerHTML'))
      .map(({ path }) => path);
    expect(
      offenders,
      'dangerouslySetInnerHTML injects unescaped HTML. Clinical text here comes from OCR, ' +
        'from free-text fields and from LLM output, and there is no sanitiser in this ' +
        "project's dependencies to put in front of it.",
    ).toEqual([]);
  });

  it('never writes to innerHTML or outerHTML directly', () => {
    const offenders = allSources()
      .filter(({ text }) => /\.(inner|outer)HTML\s*=/.test(text))
      .map(({ path }) => path);
    expect(offenders, 'assigning innerHTML bypasses React escaping the same way').toEqual([]);
  });

  it('does not build DOM from strings via insertAdjacentHTML or document.write', () => {
    const offenders = allSources()
      .filter(({ text }) => /insertAdjacentHTML|document\.write\s*\(/.test(text))
      .map(({ path }) => path);
    expect(offenders).toEqual([]);
  });

  it('has no string-to-code evaluation', () => {
    // `new Function(...)` and `eval(...)`. Both turn a string into executable code, which for
    // any string that touched patient data or an LLM response is the same problem as innerHTML.
    const offenders = allSources()
      .filter(({ text }) => /\beval\s*\(|\bnew\s+Function\s*\(/.test(text))
      .map(({ path }) => path);
    expect(offenders).toEqual([]);
  });

  it('has no markdown or HTML renderer in the dependency tree to reintroduce it', () => {
    // The realistic way this invariant breaks is not someone typing
    // `dangerouslySetInnerHTML` — it is adding a markdown renderer to display an agent's
    // rationale, since every common one renders raw HTML by default.
    const packages = [
      resolve(__dirname, '../../package.json'),
      resolve(__dirname, '../../../../packages/ui/package.json'),
    ];
    const risky = ['marked', 'markdown-it', 'react-markdown', 'showdown', 'html-react-parser'];
    for (const manifest of packages) {
      const declared = JSON.parse(readFileSync(manifest, 'utf8'));
      const names = Object.keys({ ...declared.dependencies, ...declared.devDependencies });
      for (const name of risky) {
        expect(
          names,
          `${name} renders raw HTML by default. If it is needed, it has to arrive with a ` +
            'sanitiser and this test has to be updated deliberately.',
        ).not.toContain(name);
      }
    }
  });
});
